//
// Created by MAJ on 21/05/2023.
//

#ifndef MARIO_PARTEAM_V1_TICKETS_H
#define MARIO_PARTEAM_V1_TICKETS_H
#include "generalfunctions.h"
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define CLAVIER_WIDTH 600
#define CLAVIER_HEIGHT 200
#define TOUCHE_WIDTH 40
#define TOUCHE_HEIGHT 40
#define X_MARGE ((CLAVIER_WIDTH - 14*TOUCHE_WIDTH) / 2)
#define Y_MARGE ((CLAVIER_HEIGHT - 4*TOUCHE_HEIGHT) / 2)
#endif //MARIO_PARTEAM_V1_TICKETS_H
